name: 15 Daily Commits

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at 00:00 UTC
  workflow_dispatch: # Allows manual testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make 15 Commits
        run: |
          git config --local user.email "159695664+LAXMANRADDI@users.noreply.github.com."
          git config --local user.name "LAXMANRADDI"
          
          for i in {1..15}
          do
            echo "Commit number $i on $(date)" >> activity.txt
            git add activity.txt
            git commit -m "Automated commit $i of 15 for $(date +'%Y-%m-%d')"
          done
          
          git push
